title: Logbuch:Freiheit
url: https://logbuch-freiheit.de

### download_url: is needed, if and only if audio files are hosted in a different location, it is the path of the directory where the audio files are stored
download_url: https://logbuch-freiheit.de/episodes/
subtitle: LNP meets GFF
description: Ein Youtube-Kanal über Freiheitsrechte. Als Podcast exportiert.
author: Linus Neumann und Lea Beckmann

### author_url: This is the URL of a site owned by the author (see https://jsonfeed.org/version/1)
author_url: "https://logbuch-netzpolitik.de/"

email: logbuch_freiheit@linus-neumann.de
keywords: [Politik, Grundrechte, Freiheitsrechte, GFF]
itunes_categories: [Society & Culture]
episodes_per_feed_page: 100

player_theme: default # default | "default-dark" | legacy | minimal | republica

### Date can be localized via date_de.rb plugin, you don't need to change this
date_format: ordinal

### Rsync Deploy config: Be sure your public key is listed in your server's ~/.ssh/authorized_keys file
ssh_host: terrorbyte
ssh_port: 22
document_root: /usr/share/nginx/logbuch-freiheit.de/
rsync_delete: true

### Twiter config, optional
twitter_nick: me_netzpolitik # Twitter will not be used unless this is set

language: de
explicit: "no" # "yes" | "no" | clean

### License Config, you really should configure this
license: CC BY 4.0
license_url: https://creativecommons.org/licenses/by/4.0/
license_image_url: https://i.creativecommons.org/l/by/4.0/88x31.png

### Feed links, optional
# itunes_url: https://itunes.apple.com/at/podcast/myname/id232323
# google_play_url: https://playmusic.app.goo.gl/...
# bitlove_url: https://bitlove.org/myaccount
# fyyd_url: https://fyyd.de/podcast/myaccount/myid
# gpodder_url: https://gpodder.net/podcast/mypodcast

### Additional Feeds, optional
#  itunes: http://itunes.apple.com/de/podcast/podcast_name/id42424242
#  torrent_m4a: http://bitlove.org/example_user/example_podcast_m4a/feed
#  torrent_mp3: http://bitlove.org/example_user/example_podcast_mp3/feed

### Flattr config, optional
# flattr_uid: # Flattr will not be used unless this is set
# flattr_button: compact # compact | default
# flattr_mode: auto # auto | manual
# flattr_popout:  1 # 1 | 0 (show popout when hovering mouse over button)
# flattr_language: en_GB # available languages see https://api.flattr.com/rest/v2/languages.txt
# flattr_category: audio # available categories see https://api.flattr.com/rest/v2/categories.txt

### Disqus comments
# disqus_shortname: # Disqus will not be used unless this is set
# disqus_developer: 0 # 1 | 0

### Isso comments
use_isso: "no" # "no" | "yes"

theme: jekyll-bootflat

### Jekyll Admin: uncomment the last line of this paragraph to enable Jekyll Admin.
### (but you will loose auto regeneration after code changes with a text editor then)
plugins:
  - jekyll-octopod
#  - jekyll-admin

### Links to all domains, expect whitelisted will be rendered with rel="nofollow noopener noreferrer"
# kramdown:
#   input: 'NoopenerGFM'
#   same_tab_domains:
#     - localhost
#     - 127.0.0.1
#     - podcast.your-domain.com
